/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.text.BadLocationException;

/**
 *
 * @author ok
 */
public class adminMenu extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public adminMenu() {
        initComponents();
        setSize(900, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainLogo = new javax.swing.JLabel();
        setMembershipButton = new javax.swing.JButton();
        viewAllMembersButton = new javax.swing.JButton();
        viewFeedbackButton = new javax.swing.JButton();
        removeMembersButton = new javax.swing.JButton();
        viewBookingButton = new javax.swing.JButton();
        feedbackReportButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(227, 180, 440, 42);

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/lovely.png"))); // NOI18N
        getContentPane().add(mainLogo);
        mainLogo.setBounds(300, 60, 270, 110);

        setMembershipButton.setBackground(new java.awt.Color(255, 153, 51));
        setMembershipButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        setMembershipButton.setForeground(new java.awt.Color(0, 8, 27));
        setMembershipButton.setText("SET MEMBERSHIP");
        setMembershipButton.setAlignmentY(0.0F);
        setMembershipButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        setMembershipButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setMembershipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMembershipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setMembershipButton);
        setMembershipButton.setBounds(460, 260, 210, 40);

        viewAllMembersButton.setBackground(new java.awt.Color(255, 153, 51));
        viewAllMembersButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewAllMembersButton.setForeground(new java.awt.Color(0, 8, 27));
        viewAllMembersButton.setText("VIEW ALL MEMBERS");
        viewAllMembersButton.setAlignmentY(0.0F);
        viewAllMembersButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewAllMembersButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewAllMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllMembersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllMembersButton);
        viewAllMembersButton.setBounds(220, 260, 210, 40);

        viewFeedbackButton.setBackground(new java.awt.Color(255, 153, 51));
        viewFeedbackButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewFeedbackButton.setForeground(new java.awt.Color(0, 8, 27));
        viewFeedbackButton.setText("VIEW FEEDBACK");
        viewFeedbackButton.setAlignmentY(0.0F);
        viewFeedbackButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewFeedbackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewFeedbackButton);
        viewFeedbackButton.setBounds(460, 380, 210, 40);

        removeMembersButton.setBackground(new java.awt.Color(255, 153, 51));
        removeMembersButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        removeMembersButton.setForeground(new java.awt.Color(0, 8, 27));
        removeMembersButton.setText("REMOVE MEMBERS");
        removeMembersButton.setAlignmentY(0.0F);
        removeMembersButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        removeMembersButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMembersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeMembersButton);
        removeMembersButton.setBounds(220, 320, 210, 40);

        viewBookingButton.setBackground(new java.awt.Color(255, 153, 51));
        viewBookingButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewBookingButton.setForeground(new java.awt.Color(0, 8, 27));
        viewBookingButton.setText("VIEW BOOKINGS");
        viewBookingButton.setAlignmentY(0.0F);
        viewBookingButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewBookingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewBookingButton);
        viewBookingButton.setBounds(220, 380, 210, 40);

        feedbackReportButton.setBackground(new java.awt.Color(255, 153, 51));
        feedbackReportButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        feedbackReportButton.setForeground(new java.awt.Color(0, 8, 27));
        feedbackReportButton.setText("FEEDBACK REPORT");
        feedbackReportButton.setAlignmentY(0.0F);
        feedbackReportButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        feedbackReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        feedbackReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackReportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(feedbackReportButton);
        feedbackReportButton.setBounds(460, 320, 210, 40);

        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 480, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/ayangku_3.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedbackButtonActionPerformed
        // TODO add your handling code here:
        
        AdminPanel feedbackCheck = new AdminPanel();
        
        try {
            feedbackCheck.feedbackDisplay("feedback.txt");
        } catch (BadLocationException ex) {
            System.err.println(ex);
        }
        
      
        
    }//GEN-LAST:event_viewFeedbackButtonActionPerformed

    private void viewAllMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllMembersButtonActionPerformed
        // TODO add your handling code here:
        
         AdminPanel viewMember = new AdminPanel();
         try {
        viewMember.UsernameMembershipDisplay("members.txt");
         } catch (BadLocationException ex) {
             System.err.println(ex);
         }
         
         
    }//GEN-LAST:event_viewAllMembersButtonActionPerformed

    private void removeMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMembersButtonActionPerformed
        // TODO add your handling code here:
        
        removeMemberPage remove = new removeMemberPage();
        remove.setVisible(true);
        
        
    }//GEN-LAST:event_removeMembersButtonActionPerformed

    private void setMembershipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMembershipButtonActionPerformed
        // TODO add your handling code here:
        setMembershipPage newMembershipPage = new setMembershipPage();
        
        newMembershipPage.setVisible(true);
    }//GEN-LAST:event_setMembershipButtonActionPerformed

    private void viewBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookingButtonActionPerformed
        // TODO add your handling code here:
        
        AdminPanel viewBooking = new AdminPanel();
        
        try {
            viewBooking.bookingsDisplay("bookings.txt");
        } catch (BadLocationException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewBookingButtonActionPerformed

    private void feedbackReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackReportButtonActionPerformed
        // TODO add your handling code here:
        
        feedbackReportPage report = new feedbackReportPage();
        
        report.setVisible(true);
    }//GEN-LAST:event_feedbackReportButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        welcomePage backToWelcome = new welcomePage();
        backToWelcome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feedbackReportButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JButton removeMembersButton;
    private javax.swing.JButton setMembershipButton;
    private javax.swing.JButton viewAllMembersButton;
    private javax.swing.JButton viewBookingButton;
    private javax.swing.JButton viewFeedbackButton;
    // End of variables declaration//GEN-END:variables
}
