/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ok
 */
public class changePasswordPage extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */

    public changePasswordPage() {
        initComponents();
        setSize(900, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setUser(String username)
    {
        usernameChange.setText(username);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        usernameChange = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        oldPasswordChange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        newpassField = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        confirmpassChange = new javax.swing.JPasswordField();
        showPassword1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/lovely.png"))); // NOI18N
        getContentPane().add(mainLogo);
        mainLogo.setBounds(300, 60, 270, 110);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(227, 180, 440, 42);

        jButton3.setBackground(new java.awt.Color(255, 153, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("CHANGE PASSWORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 400, 270, 32);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Old Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 280, 90, 30);

        usernameChange.setBackground(new java.awt.Color(204, 204, 204));
        usernameChange.setToolTipText("");
        usernameChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameChangeActionPerformed(evt);
            }
        });
        usernameChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameChangeKeyPressed(evt);
            }
        });
        getContentPane().add(usernameChange);
        usernameChange.setBounds(320, 240, 270, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 240, 70, 30);

        oldPasswordChange.setBackground(new java.awt.Color(204, 204, 204));
        oldPasswordChange.setToolTipText("");
        oldPasswordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordChangeActionPerformed(evt);
            }
        });
        oldPasswordChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldPasswordChangeKeyPressed(evt);
            }
        });
        getContentPane().add(oldPasswordChange);
        oldPasswordChange.setBounds(320, 280, 270, 22);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("New Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 320, 100, 30);

        newpassField.setBackground(new java.awt.Color(204, 204, 204));
        newpassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(newpassField);
        newpassField.setBounds(320, 320, 270, 22);

        showPassword.setBackground(new java.awt.Color(0, 0, 0));
        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(showPassword);
        showPassword.setBounds(600, 320, 140, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Confirm New Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 360, 140, 30);

        confirmpassChange.setBackground(new java.awt.Color(204, 204, 204));
        confirmpassChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassChangeActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpassChange);
        confirmpassChange.setBounds(320, 360, 270, 22);

        showPassword1.setBackground(new java.awt.Color(0, 0, 0));
        showPassword1.setForeground(new java.awt.Color(255, 255, 255));
        showPassword1.setText("Show Password");
        showPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(showPassword1);
        showPassword1.setBounds(600, 360, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/ayangku_3.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MemberPanel changePass = new MemberPanel();
        
        char[] newPass = newpassField.getPassword();
        String newestPass = new String(newPass);
        
        changePass.changePassword(usernameChange.getText(), oldPasswordChange.getText(), newestPass, "members.txt");
        
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void usernameChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameChangeActionPerformed

    private void usernameChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameChangeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameChangeKeyPressed

    private void oldPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordChangeActionPerformed

    private void oldPasswordChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPasswordChangeKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_oldPasswordChangeKeyPressed

    private void newpassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassFieldActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:

        if (showPassword.isSelected())
        {
            newpassField.setEchoChar((char)0);
        }
        else
        {
            newpassField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void confirmpassChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassChangeActionPerformed

    private void showPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword1ActionPerformed
        // TODO add your handling code here:

        if (showPassword1.isSelected())
        {
            confirmpassChange.setEchoChar((char)0);
        }
        else
        {
            confirmpassChange.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePasswordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmpassChange;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JPasswordField newpassField;
    private javax.swing.JTextField oldPasswordChange;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JCheckBox showPassword1;
    private javax.swing.JTextField usernameChange;
    // End of variables declaration//GEN-END:variables
}
