/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author ok
 */
public class memberMenu extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public memberMenu() {
        initComponents();
        setSize(900, 600);
    }
    
    public void setUser(String username)
    {
        nameOfUser.setText(username);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainLogo = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        viewPersonalInfoButton = new javax.swing.JButton();
        viewStoreButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        viewTrainerButton = new javax.swing.JButton();
        nameOfUser = new javax.swing.JLabel();
        feedbackButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEMBER MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(227, 180, 440, 42);

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/lovely.png"))); // NOI18N
        getContentPane().add(mainLogo);
        mainLogo.setBounds(300, 60, 270, 110);

        changePasswordButton.setBackground(new java.awt.Color(255, 153, 51));
        changePasswordButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        changePasswordButton.setForeground(new java.awt.Color(0, 8, 27));
        changePasswordButton.setText("CHANGE PASSWORD");
        changePasswordButton.setAlignmentY(0.0F);
        changePasswordButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        changePasswordButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changePasswordButton);
        changePasswordButton.setBounds(320, 440, 250, 40);

        viewPersonalInfoButton.setBackground(new java.awt.Color(255, 153, 51));
        viewPersonalInfoButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewPersonalInfoButton.setForeground(new java.awt.Color(0, 8, 27));
        viewPersonalInfoButton.setText("VIEW PERSONAL DETAILS");
        viewPersonalInfoButton.setAlignmentY(0.0F);
        viewPersonalInfoButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewPersonalInfoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewPersonalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonalInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewPersonalInfoButton);
        viewPersonalInfoButton.setBounds(320, 260, 250, 40);

        viewStoreButton.setBackground(new java.awt.Color(255, 153, 51));
        viewStoreButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewStoreButton.setForeground(new java.awt.Color(0, 8, 27));
        viewStoreButton.setText("VIEW STORE");
        viewStoreButton.setAlignmentY(0.0F);
        viewStoreButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewStoreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewStoreButton);
        viewStoreButton.setBounds(320, 380, 250, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 90, 17);

        viewTrainerButton.setBackground(new java.awt.Color(255, 153, 51));
        viewTrainerButton.setFont(new java.awt.Font("Uni Sans Bold", 1, 20)); // NOI18N
        viewTrainerButton.setForeground(new java.awt.Color(0, 8, 27));
        viewTrainerButton.setText("VIEW TRAINER");
        viewTrainerButton.setAlignmentY(0.0F);
        viewTrainerButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 102, 0)));
        viewTrainerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrainerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewTrainerButton);
        viewTrainerButton.setBounds(320, 320, 250, 40);

        nameOfUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameOfUser.setForeground(new java.awt.Color(255, 255, 255));
        nameOfUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOfUser.setText("jLabel4");
        getContentPane().add(nameOfUser);
        nameOfUser.setBounds(40, 60, 70, 17);

        feedbackButton.setBackground(new java.awt.Color(102, 102, 102));
        feedbackButton.setForeground(new java.awt.Color(255, 255, 255));
        feedbackButton.setText("Give us your Feedback!");
        feedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(feedbackButton);
        feedbackButton.setBounds(30, 480, 180, 40);

        logoutButton.setText("LOG OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(400, 500, 100, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/ayangku_3.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStoreButtonActionPerformed
        // TODO add your handling code here:
        viewStorePage storePage = new viewStorePage();
        
        storePage.setVisible(true);
    }//GEN-LAST:event_viewStoreButtonActionPerformed

    private void viewPersonalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonalInfoButtonActionPerformed
        // TODO add your handling code here:
       MemberPanel member = new MemberPanel();
        try {
            member.displayMemberDetails(nameOfUser.getText());
        } catch (BadLocationException ex) {
            
        }
    }//GEN-LAST:event_viewPersonalInfoButtonActionPerformed

    private void viewTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrainerButtonActionPerformed
        // TODO add your handling code here:
       
       trainersPage trainer = new trainersPage();
       trainer.setUser(nameOfUser.getText());
       trainer.setVisible(true);
       
        
    }//GEN-LAST:event_viewTrainerButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        // TODO add your handling code here:
        changePasswordPage changePassPage = new changePasswordPage();
        
        changePassPage.setUser(nameOfUser.getText());
        changePassPage.setVisible(true);
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void feedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackButtonActionPerformed
        // TODO add your handling code here:
        feedbackPage feedback = new feedbackPage();
        
        feedback.setVisible(true);
        
    }//GEN-LAST:event_feedbackButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        welcomePage backToWelcome = new welcomePage();
        backToWelcome.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memberMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton feedbackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel nameOfUser;
    private javax.swing.JButton viewPersonalInfoButton;
    private javax.swing.JButton viewStoreButton;
    private javax.swing.JButton viewTrainerButton;
    // End of variables declaration//GEN-END:variables
}
