/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ok
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public signUp() {
        initComponents();
        setSize(900, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameFieldSignup = new javax.swing.JTextField();
        passwordFieldSignup = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirmpassFieldSignup = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        nameFieldSignup = new javax.swing.JTextField();
        above15 = new javax.swing.JCheckBox();
        showPassword = new javax.swing.JCheckBox();
        showPassword1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        mainLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/lovely.png"))); // NOI18N
        getContentPane().add(mainLogo);
        mainLogo.setBounds(300, 60, 270, 110);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 180, 257, 42);

        usernameFieldSignup.setBackground(new java.awt.Color(204, 204, 204));
        usernameFieldSignup.setToolTipText("");
        usernameFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldSignupActionPerformed(evt);
            }
        });
        getContentPane().add(usernameFieldSignup);
        usernameFieldSignup.setBounds(320, 290, 270, 26);

        passwordFieldSignup.setBackground(new java.awt.Color(204, 204, 204));
        passwordFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldSignupActionPerformed(evt);
            }
        });
        getContentPane().add(passwordFieldSignup);
        passwordFieldSignup.setBounds(320, 330, 270, 26);

        signUpButton.setBackground(new java.awt.Color(255, 153, 51));
        signUpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signUpButton.setText("SIGN UP");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton);
        signUpButton.setBounds(320, 440, 270, 36);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 290, 60, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 330, 60, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 370, 110, 30);

        confirmpassFieldSignup.setBackground(new java.awt.Color(204, 204, 204));
        confirmpassFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassFieldSignupActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpassFieldSignup);
        confirmpassFieldSignup.setBounds(320, 370, 270, 26);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 250, 60, 30);

        nameFieldSignup.setBackground(new java.awt.Color(204, 204, 204));
        nameFieldSignup.setToolTipText("");
        nameFieldSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldSignupActionPerformed(evt);
            }
        });
        getContentPane().add(nameFieldSignup);
        nameFieldSignup.setBounds(320, 250, 270, 26);

        above15.setBackground(new java.awt.Color(0, 0, 0));
        above15.setForeground(new java.awt.Color(255, 255, 255));
        above15.setText("I am above 15 years of age");
        getContentPane().add(above15);
        above15.setBounds(320, 410, 270, 20);

        showPassword.setBackground(new java.awt.Color(0, 0, 0));
        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(showPassword);
        showPassword.setBounds(600, 330, 140, 30);

        showPassword1.setBackground(new java.awt.Color(0, 0, 0));
        showPassword1.setForeground(new java.awt.Color(255, 255, 255));
        showPassword1.setText("Show Password");
        showPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(showPassword1);
        showPassword1.setBounds(600, 370, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/assets/ayangku_3.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void usernameFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldSignupActionPerformed

    private void passwordFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldSignupActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        
        AccountSystem signup = new AccountSystem();
        
        
        String username = usernameFieldSignup.getText();
        char[] password = passwordFieldSignup.getPassword();
        char[] confirmPassword = confirmpassFieldSignup.getPassword();

        if (!above15.isSelected()) {
            JOptionPane.showMessageDialog(this, "You must be above 15 years old!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!signup.PasswordMatch(password, confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.\nMake sure that both the password and confirm-password fields match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        // Save data to a file
        if (signup.saveCredentials(username, password) == true)
        {
            this.dispose();
            JOptionPane.showMessageDialog(this, "Account saved in database, successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            User user = new User(username); // polymorph
            membershipPage f1 = new membershipPage();
            
            f1.setUser(user);
            f1.setVisible(true);
        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Error in saving the account, please retry!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
        
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void confirmpassFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassFieldSignupActionPerformed

    private void nameFieldSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldSignupActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:

        if (showPassword.isSelected())
        {
            passwordFieldSignup.setEchoChar((char)0);
        }
        else
        {
            passwordFieldSignup.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void showPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword1ActionPerformed
        // TODO add your handling code here:

        if  (showPassword1.isSelected())
        {
            confirmpassFieldSignup.setEchoChar((char)0);
        }
        else
        {
            confirmpassFieldSignup.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox above15;
    private javax.swing.JPasswordField confirmpassFieldSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JTextField nameFieldSignup;
    private javax.swing.JPasswordField passwordFieldSignup;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JCheckBox showPassword1;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField usernameFieldSignup;
    // End of variables declaration//GEN-END:variables
}
